# Build stage
FROM golang:1.23-alpine AS build

# Install curl
RUN apk add --no-cache curl

# Create the working directory
WORKDIR /go/src/app

# Copy go.mod and go.sum to the working directory
COPY ./src/go.mod ./src/go.sum ./

# Download Go module dependencies
RUN go mod download

# Copy the entire source code into the working directory
COPY ./src ./

# Build the Go application
RUN go build -o app .

# Final stage
FROM alpine:3.18

# Create a directory for the app
RUN mkdir -p /app

# Copy the built app from the previous stage
COPY --from=build /go/src/app/app /app/

WORKDIR /app

# Define the command to run the application
CMD ["./app"]
